[build]
command = "pnpm install && NODE_OPTIONS='--max-old-space-size=4096' pnpm nx run tresjs-lab:generate"
publish = "apps/docs/dist"

[build.environment]
COREPACK_INTEGRITY_KEYS = "0"
NODE_VERSION = "22"