[build]
command = "pnpm install && NODE_OPTIONS='--max-old-space-size=4096' pnpm nx run cientos-docs-vitepress:build"
publish = "apps/cientos-docs-vitepress/.vitepress/dist"

[build.environment]
COREPACK_INTEGRITY_KEYS = "0"
NODE_VERSION = "22"

[[redirects]]
from = "/*"
to = "/200.html"
status = 200
